FROM fluent/fluentd:v1.12.0-1.0


USER root

RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install fluent-plugin-elasticsearch \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /home/fluent/.gem/ruby/*/cache/*.gem

COPY fluent.es.conf  /fluentd/etc/fluent.conf
COPY entrypoint.sh /bin/

USER fluent
